<?php

declare(strict_types=1);

namespace MTL\Core;

defined('MTL_APP') || exit;

/**
 * PSR-4 autoloader.
 *
 * Strato has no Composer, so the application ships its own. A generated
 * classmap (bin/console.php optimize) short-circuits the filesystem lookup on
 * production; without it the loader falls back to resolving paths per class.
 */
final class Autoloader
{
    /** @var array<string,string> namespace prefix => base directory */
    private static array $prefixes = [];

    /** @var array<class-string,string> fully qualified class name => file */
    private static array $classmap = [];

    private static bool $registered = false;

    /**
     * @param array<string,string> $prefixes namespace prefix => base directory
     */
    public static function register(array $prefixes): void
    {
        foreach ($prefixes as $prefix => $dir) {
            self::$prefixes[trim($prefix, '\\') . '\\'] = rtrim($dir, '/\\');
        }

        $cached = MTL_ROOT . '/storage/cache/classmap.php';
        if (is_file($cached)) {
            /** @var array<class-string,string> $map */
            $map = require $cached;
            if (is_array($map)) {
                self::$classmap = $map;
            }
        }

        if (!self::$registered) {
            spl_autoload_register([self::class, 'load'], true, false);
            self::$registered = true;
        }
    }

    public static function load(string $class): void
    {
        if (isset(self::$classmap[$class]) && is_file(self::$classmap[$class])) {
            require self::$classmap[$class];
            return;
        }

        foreach (self::$prefixes as $prefix => $dir) {
            if (!str_starts_with($class, $prefix)) {
                continue;
            }

            $relative = substr($class, strlen($prefix));
            $file = $dir . '/' . str_replace('\\', '/', $relative) . '.php';

            if (is_file($file)) {
                require $file;
                return;
            }
        }
    }

    /**
     * Walks the registered prefixes and writes a classmap, turning every
     * subsequent autoload into a single array lookup.
     *
     * @return int number of classes mapped
     */
    public static function buildClassmap(): int
    {
        $map = [];

        foreach (self::$prefixes as $prefix => $dir) {
            if (!is_dir($dir)) {
                continue;
            }

            $files = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS)
            );

            foreach ($files as $file) {
                /** @var \SplFileInfo $file */
                if ($file->getExtension() !== 'php') {
                    continue;
                }

                $relative = substr($file->getPathname(), strlen($dir) + 1);
                $class = $prefix . str_replace('/', '\\', substr($relative, 0, -4));

                // Only map files that actually declare the class the path
                // implies; helpers.php and routes.php do not.
                $source = (string) file_get_contents($file->getPathname());
                $short = substr($class, strrpos($class, '\\') + 1);
                if (preg_match('/^\s*(?:final\s+|abstract\s+)?(?:class|interface|trait|enum)\s+' . preg_quote($short, '/') . '\b/m', $source)) {
                    $map[$class] = $file->getPathname();
                }
            }
        }

        ksort($map);

        $export = "<?php\n\n// Generated by bin/console.php optimize. Safe to delete.\n\nreturn " . var_export($map, true) . ";\n";
        $target = MTL_ROOT . '/storage/cache/classmap.php';

        if (!is_dir(dirname($target))) {
            mkdir(dirname($target), 0775, true);
        }
        file_put_contents($target, $export, LOCK_EX);

        return count($map);
    }
}
